HOSTNAME = '127.0.0.1'
PORT=3306
DATABASE = 'IoTCamera'
USERNAME = 'root'
PASSWORD = '123456'
DB_URI = 'mysql+mysqldb://{}:{}@{}:{}/{}'.format(USERNAME, PASSWORD, HOSTNAME, PORT, DATABASE)
SQLALCHEMY_DATABASE_URI=DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS=True
PHOTO_BASE_PATH = r'/Users/xinjiezeng/PycharmProjects/flaskProject/images/'
DETECT_FACE_URL = 'https://api-cn.faceplusplus.com/facepp/v3/detect'
COMPARE_FACE_URL = 'https://api-cn.faceplusplus.com/facepp/v3/compare'
GARAGE_CREDENTIAL_URL = 'https://api.myqdevice.com/api/v5/Login'
KEY = "vTLWlxe8ooTcPutTopW624ANrOthhNeh"
SECRET = "yD118XLLTEaJCh4N2Zzs0XzJHViobsFL"
MY_Q_USERNAME = 'jianhuizhu1987@outlook.com'
MY_Q_PASSWORD = 'ivGmt9fs'
