version: '3'

services:
  mysql:
    container_name: mysql-container #给mysql容器起一个名字
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: IoTCamera #对于拉取后的mysql，此名称用来创建一个空数据库，之后可导入数据
      MYSQL_ROOT_PASSWORD: 123456 #数据库密码
    ports:
      - "3306:3306"
    volumes:
      - ~/Users/xinjiezeng/mysql:/var/lib/mysql
    restart: always
    user: root
  flaskproject:
    restart: always
    build: .
    ports:
      - "5000:5000"#端口映射 把宿主机的端口9091（第一个）映射到容器的端口8080（第二个）
    depends_on:
      - mysql #这里的名称和第三行服务名称保持一致